### ISSUE TITLE
请问下windows编译，mac下无法运行

### ISSUE THREAD

**Issue by SmallWeed** [lzyy/flutter-demo-topmovies#2]
请问下windows编译，mac下无法运行怎么处理。

会报错 

xiaocaodeiMac:myapp xiaocao$ flutter run
Warning! This package referenced a Flutter repository via the .packages file
that is no longer available. The repository from which the 'flutter' tool is
currently executing will be used instead.
  running Flutter tool: /Users/xiaocao/Desktop/flutter
  previous reference  : /E:/FlutterSDK/flutter
This can happen if you deleted or moved your copy of the Flutter repository, or
if it was on a volume that is no longer mounted or has been mounted at a
different location. Please check your system path to verify that you are running
the expected version (run 'flutter --version' to see which flutter is on your
path).

Your application could not be compiled, because its dependencies could not be
established.
The following Dart file:
  /Users/xiaocao/Desktop/myapp/lib/main.dart
...refers, in an import, to the following library:
  /E:/FlutterSDK/flutter/packages/flutter/lib/material.dart
Unfortunately, that library does not appear to exist on your file system.

**Comment by limboy** [comment]
尽量在一个环境下编译和运行吧
